# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 9006:5432
    volumes:
      - "./postgres.sql:/docker-entrypoint-initdb.d/01init-database.sql"
      - "./inserts.sql:/docker-entrypoint-initdb.d/02inserts.sql"
      - "./dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9007:8080
